ADD new parameters to help desk mail
open-uchile/eol_contact_form pull request #1
Opened 2024-07-24 21:06 UTC by catalinaIlabaca

Add new  parameters has user mail, referrer and if exists course referrer

2024-07-24 21:59 UTC, fsologureng requested changes

2024-07-24 21:59 UTC, fsologureng commented on eol_contact_form/views.py
> +            user_form_referrer_course=re.findall('course-v1:[^/+]+?\+[^/+]+?\+[^/]+',data['form-referrer'])
Sacar `?`, están de más.

2024-07-24 21:59 UTC, fsologureng commented on eol_contact_form/templates/emails/help_desk_email.txt
> +        <p>${_("Referrer:")} <strong>${user_form_referrer}</strong>.</p>
Usar otro texto más amable con el operador de la mesa de ayuda, como "Página previa" (Previous page), y "Código de curso de la página previa:" (Previous page course code).

2024-07-25 15:14 UTC, tomaspemora commented on eol_contact_form/templates/eol_contact_form/contact.html
En este archivo solo veo un cambio real en la línea 43 en el que se agrega el input oculto para el referer, pero se muestra como si se estuviera cambiando el archivo completo.

2024-07-25 15:24 UTC, fsologureng commented on eol_contact_form/templates/eol_contact_form/contact.html
Ayer vimos la configuración del Visual Studio con Cata para que dejara de commitear saltos de linea en formato windows y lo hiciera en formato unix (tenemos código con ambos tipos en 1 mismo archivo), lo que resultó en el  cambio del archivo completo en ese aspecto. Para el review, sólo ver el cambio lógico omitiendo eso de formato pero que igual queremos mejorar.

2024-07-25 17:56 UTC, fsologureng approved these changes

2024-07-25 19:06 UTC, tomaspemora approved these changes

2024-07-26 19:55 UTC, merged