feat: add locale translations
open-uchile/eol_contact_form pull request #4
Opened 2024-08-29 19:57 UTC by catalinaIlabaca

Se agregaron las traducciones en el formulario de contacto

2024-08-29 20:06 UTC, fsologureng requested changes

2024-08-29 20:06 UTC, fsologureng commented on eol_contact_form/locale/en/LC_MESSAGES/django.po
> +# FIRST AUTHOR <EMAIL@ADDRESS>, 2024.
Agregar datos

2024-08-29 20:06 UTC, fsologureng commented on eol_contact_form/locale/en/LC_MESSAGES/django.po
> +"Report-Msgid-Bugs-To: help-open@uchile.cl\n"
reportar a eol-ing, no a la mesa de ayuda

2024-08-29 20:06 UTC, fsologureng commented on requirements.txt
> +Django==1.11.14
La versión del edx koa es 2.2.24. Actualizar para compatibilidad.

2024-08-29 20:06 UTC, fsologureng commented on setup.py
> +    version="0.0.2",
Las features aumentan la minor version. No la patch version. Debe quedar en 0.1.0.

2024-08-29 22:07 UTC, fsologureng requested changes

2024-08-29 22:07 UTC, fsologureng commented on eol_contact_form/locale/en/LC_MESSAGES/djangojs.po
> +"Report-Msgid-Bugs-To: help-open@uchile.cl\n"
Idem acá.

2024-08-29 22:07 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +"Report-Msgid-Bugs-To: help-open@uchile.cl\n"
Ídem

2024-08-29 22:07 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/djangojs.po
> +"Report-Msgid-Bugs-To: help-open@uchile.cl\n"
Ídem

2024-08-29 23:04 UTC, tomaspemora approved these changes

2024-08-30 14:08 UTC, fsologureng requested changes
Veo 3 problemas aún:
- Faltas ortográficas. Deben ser corregidas.
- Repetición en las traducciones. Algo anda mal en la generación y significará o duplicar esfuerzos futuros o acarrear con código inútil.
- Hay diferencias demasiado importantes entre la versión en inglés y la versión en castellano que no tengo claro si es resorte de este PR o no. Yo lo corregiría al tiro, pero lo dejo a criterio de @tomaspemora.

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgstr "(Usuario: {user_username}){strong_tag_close} a creado un ticket en la plataforma "
typo: se escribe "ha creado un ticket"

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgstr "(Usuario: {user_username}){strong_tag_close} a creado un ticket en la plataforma "
"ha creado"

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/en/LC_MESSAGES/django.po
> +msgid "Help desk hours (GMT-4): from 09:00 until 18:00 (Monday - Friday)"
El horario de atención no es siempre GMT-4. Cambiar la zona horaria por América/Santiago.

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgstr "Horario de atención (GMT-3): Lunes a Viernes de 9:00 a 18:00 Hrs"
Cambiar la zona del horario de atención acorde aquí una vez que cambie el msgid.

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgstr "Espera a que nuestra mesa de ayuda se ponga en contacto contigo."
La traducción sería más bien "Nuestra mesa de ayuda le responderá lo antes posible".

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgstr "Espera a que nuestra mesa de ayuda se ponga en contacto contigo."
Si no, cambiar la versión en inglés a "Wait for our help desk to contact you"

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgid "Related to:"
Cambiar mensaje en inglés a traducción más literal

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgid "Specific Course"
Cambiar versión en inglés.

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgid "Login"
Cambiar versión en inglés

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgid "Enter the course name"
Cambiar versión en inglés

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgid "Enter your questions and queries here"
Cambiar mensaje en inglés:
"Enter your questions and queries in this text field"

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgid "Submit"
Cambiar mensaje en inglés para igualar frase

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/djangojs.po
> +msgstr "(Usuario: {user_username}){strong_tag_close} a creado un ticket en la plataforma "
ha creado

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/djangojs.po
> +msgstr "(Usuario: {user_username}){strong_tag_close} a creado un ticket en la plataforma "
ha creado

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/djangojs.po
> +msgstr "Horario de atención (GMT-3): Lunes a Viernes de 9:00 a 18:00 Hrs"
Cambiar zona horaria a América/Santiago

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/djangojs.po
> +msgstr "Horario de atención (GMT-3): Lunes a Viernes de 9:00 a 18:00 Hrs"
"Intente de nuevo"

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/en/LC_MESSAGES/djangojs.po
> +msgid "There was a problem trying to generate your ticket."
"There was a problem trying to send your message". Cambiar formulario acorde. El error no es al generar el ticket, eso es otro sistema (OTRS) del cual el edx ni se entera. El problema ocurriría en este caso si es que el formulario no se puede enviar.

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/djangojs.po
> +msgid "Submit"
Cambiar mensaje en inglés

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/djangojs.po
No entiendo por qué este archivo tiene las mismas palabras (o casi) que el no js.

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/djangojs.po
> +msgid "Related to:"
Igualar. Pero vuelvo a preguntarme por qué esto se traduce 2 veces.

2024-08-30 14:08 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/djangojs.po
> +msgid "Related to:"
Ídem siguientes.

2024-08-30 14:16 UTC, catalinaIlabaca commented on eol_contact_form/locale/es_419/LC_MESSAGES/djangojs.po
> +msgid "Related to:"
Se generaron de forma automatica con el  create_translations_catalogs

2024-08-30 14:30 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/djangojs.po
> +msgid "Related to:"
claro, tiene que haber un problema en el config de babel o algo así

2024-08-30 14:33 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/djangojs.po
> +msgid "Related to:"
el único js que hay, no tiene textos, y no hay plantillas undercores que se agreguen como plantillas html en la página, entonces sólo debería haber archivos `django.po`

2024-09-02 14:12 UTC, fsologureng requested changes

2024-09-02 14:12 UTC, fsologureng commented on Makefile
> +        pybabel init -i eol_contact_form/locale/django.pot -D django -d eol_contact_form/locale/ -l $$lang ; \
Estoy mirando el archivo subido y sigo viendo que te cambia la indentación. Algo debe andar mal con tu visual studio.

2024-09-02 14:12 UTC, fsologureng commented on requirements.txt
Qué pasa si instalas en el container con estas dependencias pero sin restricciones? (eliminando los ==)
Si funciona, mover el `requirements.txt` a `requirements.in` quitándole los `==`.

2024-09-02 14:12 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgstr "Código del curso:"
No es literal la traducción.

2024-09-02 14:12 UTC, fsologureng commented on README.md
> +5. Compile the modified .po
"Compile the modified .po into .mo"
(para evitar malos entendidos)

2024-09-02 14:12 UTC, fsologureng commented on eol_contact_form/locale/en/LC_MESSAGES/django.po
> +"(Username: {user_username}){strong_tag_close} has created a ticket "
Este string no se condice con lo que pasa en la realidad. El form sólo se encarga de mandar un email. El ticket lo crea OTRS leyendo la bandeja de entrada. No creo que sea bueno amarrar conceptos de plataformas distintas.

2024-09-02 14:12 UTC, fsologureng commented on eol_contact_form/locale/en/LC_MESSAGES/django.po
> +"Help desk hours ( America/Santiago ): from 09:00 until 18:00 (Monday - "
quitar los espacios en blanco alrededor de America/Santiago dentro de los paréntesis, viene otro paréntesis después y no tiene ese formato.
Si es un problema de colisión de strings con upstream, entonces usar los paréntesis como parte del string.

2024-09-02 14:12 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +"Help desk hours ( America/Santiago ): from 09:00 until 18:00 (Monday - "
quitar espacios que envuelven dentro del paréntesis

2024-09-02 14:12 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +"Horario de atención ( America/Santiago ): Lunes a Viernes de 9:00 a 18:00"
quitar espacios que rodean paréntesis...

2024-09-02 14:12 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +"Language-Team: es_419 <LL@li.org>\n"
Este campo lo cambiaría a mano apuntando a eol-ing tb...

2024-09-02 14:12 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/djangojs.po
> +"Language-Team: es_419 <LL@li.org>\n"
Ídem otro .po

2024-09-02 15:32 UTC, catalinaIlabaca commented on Makefile
> +        pybabel init -i eol_contact_form/locale/django.pot -D django -d eol_contact_form/locale/ -l $$lang ; \
Estaba con espacio y no con tabular, corregido al tabular

2024-09-02 15:44 UTC, catalinaIlabaca commented on eol_contact_form/locale/en/LC_MESSAGES/django.po
> +"(Username: {user_username}){strong_tag_close} has created a ticket "
Pero este es el contenido del mail que llega a la mesa de ayuda y cuando llega esto es lo que se muestra, tu dices que dejemos que usuario a enviado un mail?

2024-09-02 15:52 UTC, fsologureng commented on eol_contact_form/locale/en/LC_MESSAGES/django.po
> +"(Username: {user_username}){strong_tag_close} has created a ticket "
Sí, usuario **ha** enviado un mensaje a la mesa de ayuda

2024-09-02 17:02 UTC, fsologureng requested changes
Está bacán.
Sólo me sigue haciendo ruido que se induce el contacto a una consulta cuando en verdad puede ser un reporte de error o directamente reclamo. Esto se ve en varios textos y sugiero cambiarlo por algo más genérico.
Sé que es latero y parece menor, pero este form es nuestra cara más visible y de su éxito depende que no matemos al mensajero.

2024-09-02 17:02 UTC, fsologureng commented on eol_contact_form/locale/en/LC_MESSAGES/django.po
> +"Language-Team: en <LL@li.org>\n"
Faltó este

2024-09-02 17:02 UTC, fsologureng commented on eol_contact_form/templates/eol_contact_form/contact.html
> +                        <input class="form-course-name form-control" type="text" id="form-course" name="form-course" placeholder='${_("Enter the name of the course with doubts")}' value="${data['form
Puchas, no caché esto antes: No necesariamente la gente contacta por dudas, puede ser por errores y puede ser que no haya curso tb. Sugiero un mensaje más genérico como "Nombre del curso, si aplica a su situación".

2024-09-02 17:02 UTC, fsologureng commented on eol_contact_form/templates/eol_contact_form/contact.html
> +                        <input disabled class="btn mx-auto my-3 py-2 px-5 form-submit" type="submit" value="${_('Submit inquiry')}">
Submit request? :face_with_diagonal_mouth:

2024-09-02 17:02 UTC, fsologureng commented on Makefile
Todavía hay espacios dobles separando los flags de los comandos

2024-09-02 17:12 UTC, fsologureng requested changes
Importantes que no vi de inmediato si no hasta revisar los mensajes de review previos

2024-09-02 17:12 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +"(Usuario: {user_username}){strong_tag_close} ha creado un ticket en la "
sigue la mención al ticket

2024-09-02 17:12 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +"(Usuario: {user_username}){strong_tag_close} ha creado un ticket en la "
Ídem acá

2024-09-02 17:12 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgstr ""Código del curso de la página anterior:"
typo

2024-09-04 22:56 UTC, fsologureng requested changes
Lamento la cantidad de petición de cambios, pero no contaba con el agregado del listado de cursos via API. Yo estaba listo para aprobar el refactor consensuado con DI que ya estaba a punto.

@tomaspemora Yo eliminaría la nueva funcionalidad del selector de cursos porque requiere un selector muy inteligente para limitar la sobrecarga de algunos casos patológicos y para no matar al mensajero en esos casos. Ya tenemos la captura del referrer que nos da una idea bastante acertada de qué curso estamos hablando.

@catalinaIlabaca como consejo para el futuro: Es bueno squashear los commits, pero tb es bueno separar las cosas en los commits. Si hubieras hecho una primera versión del refactor-acuerdo-DI y encima de eso un nuevo commit para agregar el selector basado en API, sería más fácil ahora el refactor que te pido para eso. Esto tb sirve para usar la semántica en la glosa de cada commit (fix, feat, docs, chore) y permite usar la funcionalidad de GitHub de sólo hacer review del último commit. Siempre se puede hacer squash al final y así no pones en riesgo lo que ya lograste y te facilita la vuelta atrás en caso de que algo de lo que te piden requiere muchos cambios pero ya tienes cambios que están consensuados.

2024-09-04 22:56 UTC, fsologureng commented on eol_contact_form/locale/en/LC_MESSAGES/django.po
> +#~ msgid "Fill out the form and our help desk will contact you shortly."
Dado que es la 1ra vez que se traduce, estos strings "previos" no son necesarios de mantener. Piensa que todos los cambios al form son "first time", y no vuelvas a correr comandos, simplemente borra de la linea en blanco pa'bajo y commit

2024-09-04 22:56 UTC, fsologureng commented on eol_contact_form/static/eol_contact_form/js/main.js
> +        const list_course = [
Pasar todos valores de campos directo al HTML, incluyendo el "Other".
De esa forma, la funcionalidad sigue siendo la misma y no hay que modificar el JS cuando cambia el form.
En general, todo lo que pueda estar en el HTML debe ir en el HTML; eso es diseño semántico y favorece la separación de capas, incluida la traducción. Siempre intentar separar el contenido de la funcionalidad.

2024-09-04 22:56 UTC, fsologureng commented on eol_contact_form/static/eol_contact_form/js/main.js
> +    async function is_logged(){
el nombre sugiere que esta función sólo responde si el usuario está logueado, no debería retornar una lista de cursos, cambiar el nombre de la función para que refleje lo que hace.

2024-09-04 22:56 UTC, fsologureng commented on eol_contact_form/templates/eol_contact_form/contact.html
> +                                issuance_of_certificates_selected = 'selected' if data['form-type'] == 'issuance_of_certificates' else ''
Este código es infernalmente ineficiente. Para pocas variables era sustentable, para todas las que hay ahora, ya no. Cambiar por un test en cada option para ver si es selected o no. Debería ser suficiente con algo como:
```
${'selected' if data['form-type'] == 'aaaaa'}
```
o similar.

2024-09-04 22:56 UTC, fsologureng commented on eol_contact_form/templates/eol_contact_form/contact.html
> +                            <option disabled selected value="">${_("Select a category")}</option>
Esta opción falsa no debiera estar marcada como selected si hay algún dato en `data['form-type']`.

2024-09-04 22:56 UTC, fsologureng commented on eol_contact_form/static/eol_contact_form/js/main.js
> +            let list_user_courses=  await is_logged();
Esta debiera ser una variable que se puebla 1 sola vez. Si no se ha consultado antes, se puebla, si no, cualquier cambio que se produzca en el form, no vuelve a recuperar los cursos. No es necesario hacerlo cada vez y aliviana mucho la interfaz para quienes tienen pocos recursos de red o de procesamiento.
Los usuarios suelen dudar entre sus opciones, siempre es bueno no sobrecargar la UI.

2024-09-04 22:56 UTC, fsologureng commented on eol_contact_form/static/eol_contact_form/js/main.js
> +            const response = await $.ajax("/api/enrollment/v1/enrollment");
Esta consulta es un problema como solución general del formulario; No todos los usuarios serán estudiantes (alguos serán profes). Por otro lado, hay casos en los cuales hay 240 inscripciones (obtenido con Thomas, justamente profes que son audit). No se puede tomar esta consulta de forma ingenua. Idealmente necesitamos un buscador de cursos con sugerencia, pero es necesario limitar bien el costo contra la api.
Por último, es necesario el fallback para los usuarios deslogueados, Para ello sería bueno ver cómo combinar ambos componentes (text input y select).

2024-09-23 19:51 UTC, catalinaIlabaca commented on eol_contact_form/templates/eol_contact_form/contact.html
> +                            <option disabled selected value="">${_("Select a category")}</option>
Es la manera en la que se crea un placeholder

2024-09-23 20:40 UTC, fsologureng commented on eol_contact_form/templates/eol_contact_form/contact.html
> +                            <option disabled selected value="">${_("Select a category")}</option>
Este `selected` muestra que todos los otros tests y variables son innecesarios; un selector no-múltiple, no puede tener más de una opción selected.

2024-09-24 12:52 UTC, fsologureng commented on eol_contact_form/templates/eol_contact_form/contact.html
> +                            <option disabled selected value="">${_("Select a category")}</option>
> Es la manera en la que se crea un placeholder

Me gustaría saber cómo es esto de que con eso se crea el placeholder, quieres decir que se ve el texto seleccionado? no es lo mismo que un placeholder...

2024-09-24 13:14 UTC, fsologureng commented on eol_contact_form/templates/eol_contact_form/contact.html
> +
Espacio de más. Quitar.

2024-09-24 13:14 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgid "form-type"
Esto no se entiende para qué e igualmente me parece que no está cumpliendo su cometido.

2024-09-24 13:14 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +"(Usuario: {user_username}){strong_tag_close}  ha enviado un mensaje a "
Doble espacio.

2024-09-24 13:14 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +"(Usuario: {user_username}){strong_tag_close}  ha enviado un mensaje a "
Doble espacio

2024-09-24 13:14 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgstr "Mensaje enviado!"
Falta el `¡` (abre exclamación)

2024-09-24 13:14 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgstr "Emisión Certificados"
"Emisión de certificados"; sin capitalizar y con el conector.

2024-09-24 13:14 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgid "Problems in progress"
Esto está mal redactado. Debe decir "Problems in the progress" y "Problemas en el avance".
"Problems in progress" significa "Problemas pendientes" o "Problemas en marcha".

2024-09-24 13:14 UTC, fsologureng commented on eol_contact_form/locale/es_419/LC_MESSAGES/django.po
> +msgstr "Ejemplo: RUT, DNI  o pasaporte"
doble espacio

2024-09-24 13:14 UTC, fsologureng commented on eol_contact_form/templates/eol_contact_form/contact.html
> +                        <input class="form-course-name form-control" type="text" id="form-course" name="form-course" placeholder='${_("Enter the name of the course with doubts")}' value="${data['form
No entendí la resolución del pedido.

2024-09-24 13:46 UTC, fsologureng requested changes

2024-09-24 13:46 UTC, fsologureng commented on eol_contact_form/views.py
> +            "user_type_message": _(data['form-type']),
Esta traducción no funciona porque el string se define en tiempo de ejecución, no de compilación de los strings. 
Ojo, como está hecho el formulario, este no envía los labels de las opciones, si no el código del option correspondiente (ej: content_of_a_course), lo cual no tiene traducción al label.
Las traducciones son para transformar entre distintos idiomas para el mismo label.
Si quieres poder transformar los códigos de los options en sus labels (mensajes amables), tendrías que tener un diccionario acá en el view para poder recuperar los strings, lo cual duplicaría los mensajes en el html como en el .py. En cambio, esta llamada se traspasa al .po y genera un string inválido (comentado antes).

Sugiero cambiar la lógica del selector para que no funcione como diccionario código (value) -> mensaje (label), si no que el value sea el mismo mensaje. Si los strings son consistentes, no deberías tener problemas en el javascript para la lógica de despliegue y requerimiento.

2024-09-24 13:46 UTC, fsologureng commented on eol_contact_form/static/eol_contact_form/js/main.js
> +        if( list_course.includes($('#form-type').val())) {
Para este test, mejor revisa si el option elegido es hijo del optgroup de los cursos. De ese modo, no tienes que explicitar todas las opciones en un arreglo y además las opciones son modificables dentro del grupo sin necesidad de modificar el javascript. Le puedes poner un marcador al optgroup si no quieres conocer su string. DOM es tu copiloto.

2024-09-24 13:46 UTC, fsologureng commented on eol_contact_form/views.py
> +            "need_course": data['form-type'] in list_course,
Complementando el comentario anterior; need_course puede ser un campo del form oculto modificado junto con los cambios en el onchange del selector de tipo.

2024-09-24 13:46 UTC, fsologureng commented on eol_contact_form/views.py
> +            "need_course": data['form-type'] in list_course,
De ese modo puede sacar el arreglo de acá tb.

2024-09-24 13:46 UTC, fsologureng commented on eol_contact_form/templates/emails/help_desk_email.txt
> +    % if need_course:
Mejor aún sería testear
```
% if user_course:
```
para evitar la necesidad de la variable `need_course`.

2024-09-25 14:40 UTC, catalinaIlabaca commented on eol_contact_form/templates/eol_contact_form/contact.html
> +                        <input class="form-course-name form-control" type="text" id="form-course" name="form-course" placeholder='${_("Enter the name of the course with doubts")}' value="${data['form
Se modifico a "Please tell us the name of the course" basado en lo lineamientos que dio catalina

2024-09-25 14:43 UTC, catalinaIlabaca commented on eol_contact_form/templates/eol_contact_form/contact.html
> +                            <option disabled selected value="">${_("Select a category")}</option>
https://www.w3docs.com/snippets/css/how-to-create-a-placeholder-for-an-html5-select-box-by-using-only-html-and-css.html

2024-09-25 15:09 UTC, fsologureng commented on eol_contact_form/templates/eol_contact_form/contact.html
> +                            <option disabled selected value="">${_("Select a category")}</option>
Ok. Volviendo al punto: el código es inconsistente en el sentido de que manipula información supuestamente almacenada en `data['form-type']` para marcar la opción seleccionada, pero eso sólo es posible si el form se renderizara como resultado de un request POST. Si así fuera, el selector quedaría mal formado porque además de la opción seleccionada como resultado de `data` estaría seleccionada la opción "placeholder".

2025-01-10 17:41 UTC, closed without merging